import React from 'react'

import skills from "../../data/skills.json";
import history from "../../data/history.json";
import styles from "./Experience.module.css";
import { getImageUrl } from './../../util';

export const Experience = () => {
    return (
        <section className={styles.container} id="experience">
            <h2 className={styles.title}>Experience</h2>
            <div className={styles.content}>
                {/* we use curly to render js data,
            then use array function called .map
            go to each element and map it to something else 
            each index inside the map, will take the skill
            and id (the id is generated by the map function)
            */}
                {/* inside the div of the return block,
            give a key inside id due to whenever you iterating through an array
            and programmatically creating elements in react
            you need to give each element an ID, then inside of it is
            their children */}
                <div className={styles.skills}>{
                    skills.map((skill, id) => {
                        return <div className={styles.skill} key={id}>
                            {/* children */}
                            <div className={styles.skillImageContainer}><img src={getImageUrl(skill.imageSrc)} alt={skill.title} /></div>
                            <p>{skill.title}</p>
                        </div>
                    })


                }

                </div>
                <ul className={styles.history}>
                    {
                        history.map((historyItem, id) => {
                            return <li key={id} className={styles.historyItem}>
                                {/* here we want alt to have string interpolation */}
                                <img
                                    src={getImageUrl(historyItem.imageSrc)}
                                    alt={`${historyItem.organisation} Logo`}
                                />
                                <div className={styles.historyItemDetails}>
                                    <h3>{`${historyItem.role},${historyItem.organisation} `}</h3>
                                    <p>{`${historyItem.startDate},${historyItem.endDate} `}</p>
                                    <ul>{historyItem.experiences.map((experience, id) => {
                                        return <li key={id}>
                                            {experience}
                                        </li>
                                    })}</ul>
                                </div>
                            </li>
                        })
                    }
                </ul>
            </div>
        </section>
    )
}
